name: Generate Snake

on:
  schedule:
    # Runs every day at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Snake
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: steepanProjects
          gif_out_path: ./output/github-contribution-grid-snake.gif
          svg_out_path: ./output/github-contribution-grid-snake.svg

      - name: Push to GitHub
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'docs: update contribution snake'
          file_pattern: 'output/*.svg output/*.gif'
